//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chipoltle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("chipoltle.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Calculate_Discounts_Weekday {
            get {
                return ResourceManager.GetString("Calculate_Discounts_Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Ingredients.
        /// </summary>
        public static string Index_cshtml_Execute_Fresh_Ingredients {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Fresh_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order &amp;nbsp;&amp;nbsp;&amp;nbsp;.
        /// </summary>
        public static string Index_cshtml_Execute_Order {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Dude.
        /// </summary>
        public static string Index_cshtml_Execute_Please_Place_an_Order {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Please_Place_an_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your classification.
        /// </summary>
        public static string Index_cshtml_Execute_Select_your_classification {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Select_your_classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Choose a Entree.
        /// </summary>
        public static string Index_cshtml_Execute_Step_1__Choose_a_Entree {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Step_1__Choose_a_Entree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Choose a Meat.
        /// </summary>
        public static string Index_cshtml_Execute_Step_2__Choose_a_Meat {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Step_2__Choose_a_Meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Choose Beans.
        /// </summary>
        public static string Index_cshtml_Execute_Step_3__Choose_Beans {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Step_3__Choose_Beans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Chipole.
        /// </summary>
        public static string Index_cshtml_Execute_Welcome_to_Chipole {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Welcome_to_Chipole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beans.
        /// </summary>
        public static string Order_Beans_Beans {
            get {
                return ResourceManager.GetString("Order_Beans_Beans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild and Crazy.
        /// </summary>
        public static string Order_Item_Wild_and_Crazy {
            get {
                return ResourceManager.GetString("Order_Item_Wild_and_Crazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat.
        /// </summary>
        public static string Order_Meat_Meat {
            get {
                return ResourceManager.GetString("Order_Meat_Meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total $.
        /// </summary>
        public static string Order_OrderCost_ {
            get {
                return ResourceManager.GetString("Order_OrderCost_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Order_OrderCost_Cost {
            get {
                return ResourceManager.GetString("Order_OrderCost_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Group.
        /// </summary>
        public static string Order_PriceGroup_Discount_Group {
            get {
                return ResourceManager.GetString("Order_PriceGroup_Discount_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corporate.
        /// </summary>
        public static string OrderSelections_CustomerGroup_corporate {
            get {
                return ResourceManager.GetString("OrderSelections_CustomerGroup_corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regular customer.
        /// </summary>
        public static string OrderSelections_CustomerGroup_regular_customer {
            get {
                return ResourceManager.GetString("OrderSelections_CustomerGroup_regular_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to student.
        /// </summary>
        public static string OrderSelections_CustomerGroup_student {
            get {
                return ResourceManager.GetString("OrderSelections_CustomerGroup_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black.
        /// </summary>
        public static string OrderSelections_SelectBeans_black {
            get {
                return ResourceManager.GetString("OrderSelections_SelectBeans_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brown.
        /// </summary>
        public static string OrderSelections_SelectBeans_brown {
            get {
                return ResourceManager.GetString("OrderSelections_SelectBeans_brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to burrito.
        /// </summary>
        public static string OrderSelections_SelectItems_burrito {
            get {
                return ResourceManager.GetString("OrderSelections_SelectItems_burrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salad.
        /// </summary>
        public static string OrderSelections_SelectItems_salad {
            get {
                return ResourceManager.GetString("OrderSelections_SelectItems_salad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taco.
        /// </summary>
        public static string OrderSelections_SelectItems_taco {
            get {
                return ResourceManager.GetString("OrderSelections_SelectItems_taco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chicken.
        /// </summary>
        public static string OrderSelections_SelectMeats_chicken {
            get {
                return ResourceManager.GetString("OrderSelections_SelectMeats_chicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steak.
        /// </summary>
        public static string OrderSelections_SelectMeats_steak {
            get {
                return ResourceManager.GetString("OrderSelections_SelectMeats_steak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to veggie.
        /// </summary>
        public static string OrderSelections_SelectMeats_veggie {
            get {
                return ResourceManager.GetString("OrderSelections_SelectMeats_veggie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Thanks_cshtml_Execute_Order {
            get {
                return ResourceManager.GetString("Thanks_cshtml_Execute_Order", resourceCulture);
            }
        }
    }
}
